<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE beans [
    <!ELEMENT beans (bean*)>
    <!ELEMENT bean (property*)>
    <!ELEMENT property (#PCDATA)>

    <!ATTLIST bean id ID #REQUIRED>
    <!ATTLIST bean class CDATA #IMPLIED>
    <!ATTLIST property name CDATA #IMPLIED>
    <!ATTLIST property ref IDREF #IMPLIED>
]>

<beans>
    <bean id="page" class="myssm.myspringmvc.PageController"/>

    <!-- DAO -->
    <bean id="userDAO" class="book.dao.impl.UserDAOImpl"/>
    <bean id="bookDAO" class="book.dao.impl.BookDAOImpl"/>
    <bean id="cartItemDAO" class="book.dao.impl.CartItemDAOImpl"/>

    <!-- service -->
    <bean id="userService" class="book.service.impl.UserServiceImpl">
        <property name="userDAO" ref="userDAO"/>
    </bean>
    <bean id="bookService" class="book.service.impl.BookServiceImpl">
        <property name="bookDAO" ref="bookDAO"/>
    </bean>
    <bean id="cartItemService" class="book.service.impl.CartItemServiceImpl">
        <property name="cartItemDAO" ref="cartItemDAO"/>
        <property name="bookService" ref="bookService"/>
    </bean>

    <!-- controller -->
    <bean id="user" class="book.controller.UserController">
        <property name="userService" ref="userService"/>
        <property name="cartItemService" ref="cartItemService"/>
    </bean>
    <bean id="book" class="book.controller.BookController">
        <property name="bookService" ref="bookService"/>
    </bean>
    <bean id="cart" class="book.controller.CartController">
        <property name="cartItemService" ref="cartItemService"/>
    </bean>

</beans>